# 将g++赋值给cc 表示用g++ 进行编译
cc        := g++
# 产生的可执行文件的名字
name      := pro
# 可执行文件的目录 以及项目以workspce为目录
workdir   := workspace

# src/文件夹
srcdir    := src

# 存放中间文件的文件夹
objdir    := objs
stdcpp    := c++11
cuda_home := /usr/local/cuda
syslib    := /usr/lib/x86_64-linux-gnu
trt_home  := /home/rex/TensorRT-8.2.0.6
# 这里是 opencv的文件夹
# cpp_pkg   := /usr/local
opencv_home := /usr/local/include/opencv4

nvcc      := $(cuda_home)/bin/nvcc -ccbin=$(cc)


# 定义cpp的路径查找和依赖项mk文件
#打印变量 可以用如下命令
# $(info  ${cpp_srcs}) 
# 用shell 命令在srcdir 中找到所有.cpp结尾的文件
# 定义cpp的路径查找和依赖项mk文件

cpp_srcs := $(shell find $(srcdir) -name "*.cpp")

# 将所有.cpp 修改为 .cpp.o
cpp_objs := $(cpp_srcs:.cpp=.cpp.o)
# 将所有.cpp.o文件的前缀 修改为 objs文件夹
cpp_objs := $(cpp_objs:$(srcdir)/%=$(objdir)/%)
# 将obj下的 .cpp.o文件的后缀 修改为 .cpp.mk文件
cpp_mk   := $(cpp_objs:.cpp.o=.cpp.mk)

# 定义cu文件的路径查找和依赖项mk文件 同上
cu_srcs := $(shell find $(srcdir) -name "*.cu")
cu_objs := $(cu_srcs:.cu=.cu.o)
cu_objs := $(cu_objs:$(srcdir)/%=$(objdir)/%)
cu_mk   := $(cu_objs:.cu.o=.cu.mk)

# 定义opencv和cuda需要用到的库文件
link_cuda      := cudart cublas
link_trtpro    := 
link_tensorRT  := 
link_opencv    := opencv_core opencv_imgcodecs opencv_imgproc
link_sys       := stdc++ dl
link_librarys  := $(link_cuda) $(link_tensorRT) $(link_sys) $(link_opencv)

# 定义头文件路径，请注意斜杠后边不能有空格
# 只需要写路径，不需要写-I
include_paths := include  \
    $(cuda_home)/include/ \
	$(trt_home)/include   \
	$(opencv_home)		  \
	$(protobuf_home)/include

# 定义库文件路径，只需要写路径，不需要写-L
# 加载动态库  不需要$(opencv_home)/opencv4.2/lib
# library_paths := $(cuda_home)/lib64 $(syslib) $(cpp_pkg)/opencv4.2/lib
library_paths := $(cuda_home)/lib64 $(syslib) 

 $(info  ${opencv_home}) 
# 把library path给拼接为一个字符串，例如a b c => a:b:c
# 然后使得LD_LIBRARY_PATH=a:b:c
empty := 
library_path_export := $(subst $(empty) $(empty),:,$(library_paths))
# 把库路径和头文件路径拼接起来成一个，批量自动加-I、-L、-l
run_paths     := $(foreach item,$(library_paths),-Wl,-rpath=$(item))
include_paths := $(foreach item,$(include_paths),-I$(item))
library_paths := $(foreach item,$(library_paths),-L$(item))
link_librarys := $(foreach item,$(link_librarys),-l$(item))

# 如果是其他显卡，请修改-gencode=arch=compute_75,code=sm_75为对应显卡的能力
# 显卡对应的号码参考这里：https://developer.nvidia.com/zh-cn/cuda-gpus#compute
# 如果是 jetson nano，提示找不到-m64指令，请删掉 -m64选项。不影响结果
cpp_compile_flags := -std=$(stdcpp) -w -g -O0 -m64 -fPIC -fopenmp -pthread
cu_compile_flags  := -std=$(stdcpp) -w -g -O0 -m64 $(cuda_arch) -Xcompiler "$(cpp_compile_flags)"
link_flags        := -pthread -fopenmp -Wl,-rpath='$$ORIGIN'

cpp_compile_flags += $(include_paths)
cu_compile_flags  += $(include_paths)
link_flags        += $(library_paths) $(link_librarys) $(run_paths)

# 如果头文件修改了，这里的指令可以让他自动编译依赖的cpp或者cu文件
ifneq ($(MAKECMDGOALS), clean)
-include $(cpp_mk) $(cu_mk)
endif

# 伪目标
# @调用shell 命令
# cd /workspace ./pro + 参数

$(name)   : $(workdir)/$(name)
all       : $(name)
run       : $(name)
	@cd $(workdir) && ./$(name) $(run_args)


# $@ 规则中的目标
# $< 规则中的第一个依赖
# $^ 规则中的所有依赖组成的数组
# workspce/pro 依赖于 %.cpp.cmk .cu.cmk
# g++ %.cpp.cmk %.cu.cmk -o /workspace/pro


# 可执行文件pro 依赖于 workspace/pro 
$(workdir)/$(name) : $(cpp_objs) $(cu_objs)
	@echo Link $@
	@mkdir -p $(dir $@)
	@$(cc) $^ -o $@ $(link_flags)

#objs 文件夹中的 %.cpp.o 依赖于 scr中的 %.cpp
$(objdir)/%.cpp.o : $(srcdir)/%.cpp
	@echo Compile CXX $<
	@mkdir -p $(dir $@)
	@$(cc) -c $< -o $@ $(cpp_compile_flags)

# objs 中的 %。cu.o 依赖于  src 下的 %.cu
$(objdir)/%.cu.o : $(srcdir)/%.cu
	@echo Compile CUDA $<
	@mkdir -p $(dir $@)
	@$(nvcc) -c $< -o $@ $(cu_compile_flags)

# 编译cpp依赖项，生成mk文件
$(objdir)/%.cpp.mk : $(srcdir)/%.cpp
	@echo Compile depends C++ $<
	@mkdir -p $(dir $@)
	@$(cc) -M $< -MF $@ -MT $(@:.cpp.mk=.cpp.o) $(cpp_compile_flags)
    
# 编译cu文件的依赖项，生成cumk文件
$(objdir)/%.cu.mk : $(srcdir)/%.cu
	@echo Compile depends CUDA $<
	@mkdir -p $(dir $@)
	@$(nvcc) -M $< -MF $@ -MT $(@:.cu.mk=.cu.o) $(cu_compile_flags)

# 定义清理指令
clean :
	@rm -rf $(objdir) $(workdir)/$(name) $(workdir)/input-image-pytorch.jpg $(workdir)/image-draw.jpg

# 防止符号被当做文件
.PHONY : clean run $(name)

# 导出依赖库路径，使得能够运行起来
export LD_LIBRARY_PATH:=$(library_path_export)