// Generated by gencpp from file base/RosImageResponse.msg
// DO NOT EDIT!


#ifndef BASE_MESSAGE_ROSIMAGERESPONSE_H
#define BASE_MESSAGE_ROSIMAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base
{
template <class ContainerAllocator>
struct RosImageResponse_
{
  typedef RosImageResponse_<ContainerAllocator> Type;

  RosImageResponse_()
    : result()  {
    }
  RosImageResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::base::RosImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base::RosImageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RosImageResponse_

typedef ::base::RosImageResponse_<std::allocator<void> > RosImageResponse;

typedef boost::shared_ptr< ::base::RosImageResponse > RosImageResponsePtr;
typedef boost::shared_ptr< ::base::RosImageResponse const> RosImageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base::RosImageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base::RosImageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base::RosImageResponse_<ContainerAllocator1> & lhs, const ::base::RosImageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base::RosImageResponse_<ContainerAllocator1> & lhs, const ::base::RosImageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base::RosImageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base::RosImageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base::RosImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base::RosImageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base::RosImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base::RosImageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base::RosImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::base::RosImageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::base::RosImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base/RosImageResponse";
  }

  static const char* value(const ::base::RosImageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base::RosImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::base::RosImageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base::RosImageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RosImageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base::RosImageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base::RosImageResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_MESSAGE_ROSIMAGERESPONSE_H
